terminate called after throwing an instance of 'std::runtime_error'
  what():  Line 7, Message: Break or continue statement invalid 
